from typing import Literal
from pydantic import BaseModel, Field


class RetrievalResult(BaseModel):
    rank: int
    chunk_id: str
    source_id: str
    score: float


class RetrievalMetrics(BaseModel):
    dominant_source_share: float = 0.0
    new_top1_source: bool = False
    answer_delta_detected: bool = False


class RetrievalEvidence(BaseModel):
    chunk_id: str
    reason: str
    rank_change: str
    answer_impact: str


class RetrievalInvestigationInput(BaseModel):
    query: str = Field(..., description="The query that triggered this investigation")
    top_k_results: list[RetrievalResult] = Field(..., description="Current top-k retrieval results")
    pre_attack_baseline_results: list[RetrievalResult] = Field(default_factory=list, description="Baseline results before the suspected attack")
    final_answer: str = Field(..., description="The answer generated by the RAG system")
    baseline_answer: str = Field(default="", description="The expected baseline answer")
    source_trust_map: dict[str, str] = Field(default_factory=dict, description="Map of source_id to trust tier")
    retrieval_metrics: RetrievalMetrics = Field(default_factory=RetrievalMetrics)


class RetrievalInvestigationOutput(BaseModel):
    query: str
    suspicious_chunk_ids: list[str]
    dominance_shift_detected: bool
    answer_corruption_detected: bool
    primary_attack_family: Literal[
        "instruction_injection", "authority_spoofing", "near_duplicate_flooding",
        "contradiction_injection", "answer_hijacking", "query_baiting",
        "ranking_manipulation", "unknown"
    ]
    severity: Literal["low", "medium", "high", "critical"]
    key_findings: list[str]
    evidence: list[RetrievalEvidence]
    confidence: float
    next_action: Literal["allow", "review", "shadow", "quarantine"]
